#Server port(command line arg i.e --port=8085 or JVM arguments -Dport=8085) and context path

server:
  port: ${port:8081}
  servlet:
    context-path: /SSAWebApp

#Profile (command line arg i.e --env=dev or -Denv=dev),View Resolver,Datasource, JPA and multipart file configuration 

spring:
  profiles:
    active: ${dev}
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: sys
  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update
              
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true
      
# logging configuration

logging:
  level:
    org.springframework: ERROR
    com.ssa: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log
  
    