//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.11 at 01:17:41 PM IST 
//

package com.ssa.federal.design_pattern.ed;

import lombok.Data;

@Data
public class PlanInfo {
	protected String planName;
	protected String planStatus;
	protected String caseNum;
	protected PlanResult planResult;
}
