//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.11 at 11:56:37 AM IST 
//

package com.ssa.ed.input;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.ssa.ed.output.PlanInfo;
import com.ssa.ed.process.IEDRules;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="citigen-data">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="first-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="last-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="case-num" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ssn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="dob" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="plan-selected" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="plan-details">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="snap-plan-data">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="family-income" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="is-employed" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ccap-plan-data">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="kids-count" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="kids-age" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="parents-employed" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="family-income" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="medicaid-plan-data">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="employment-income" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="properties-cost" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="other-income" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "citigenData", "planDetails" })
@XmlRootElement(name = "eligibility-determination")
public class EligibilityDetermination {

	@XmlElement(name = "citigen-data", required = true)
	protected EligibilityDetermination.CitigenData citigenData;
	@XmlElement(name = "plan-details", required = true)
	protected EligibilityDetermination.PlanDetails planDetails;

	/**
	 * Gets the value of the citigenData property.
	 * 
	 * @return possible object is {@link EligibilityDetermination.CitigenData }
	 * 
	 */
	public EligibilityDetermination.CitigenData getCitigenData() {
		return citigenData;
	}

	/**
	 * Sets the value of the citigenData property.
	 * 
	 * @param value allowed object is {@link EligibilityDetermination.CitigenData }
	 * 
	 */
	public void setCitigenData(EligibilityDetermination.CitigenData value) {
		this.citigenData = value;
	}

	/**
	 * Gets the value of the planDetails property.
	 * 
	 * @return possible object is {@link EligibilityDetermination.PlanDetails }
	 * 
	 */
	public EligibilityDetermination.PlanDetails getPlanDetails() {
		return planDetails;
	}

	/**
	 * Sets the value of the planDetails property.
	 * 
	 * @param value allowed object is {@link EligibilityDetermination.PlanDetails }
	 * 
	 */
	public void setPlanDetails(EligibilityDetermination.PlanDetails value) {
		this.planDetails = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within
	 * this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="first-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="last-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="case-num" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="ssn" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="dob" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="plan-selected" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "firstName", "lastName", "gender", "caseNum", "ssn", "dob", "planSelected" })
	public static class CitigenData {

		@XmlElement(name = "first-name", required = true)
		protected String firstName;
		@XmlElement(name = "last-name", required = true)
		protected String lastName;
		@XmlElement(required = true)
		protected String gender;
		@XmlElement(name = "case-num", required = true)
		protected String caseNum;
		@XmlElement(required = true)
		protected String ssn;
		@XmlElement(required = true)
		protected String dob;
		@XmlElement(name = "plan-selected", required = true)
		protected String planSelected;

		/**
		 * Gets the value of the firstName property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getFirstName() {
			return firstName;
		}

		/**
		 * Sets the value of the firstName property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setFirstName(String value) {
			this.firstName = value;
		}

		/**
		 * Gets the value of the lastName property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getLastName() {
			return lastName;
		}

		/**
		 * Sets the value of the lastName property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setLastName(String value) {
			this.lastName = value;
		}

		/**
		 * Gets the value of the gender property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getGender() {
			return gender;
		}

		/**
		 * Sets the value of the gender property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setGender(String value) {
			this.gender = value;
		}

		/**
		 * Gets the value of the caseNum property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getCaseNum() {
			return caseNum;
		}

		/**
		 * Sets the value of the caseNum property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setCaseNum(String value) {
			this.caseNum = value;
		}

		/**
		 * Gets the value of the ssn property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getSsn() {
			return ssn;
		}

		/**
		 * Sets the value of the ssn property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setSsn(String value) {
			this.ssn = value;
		}

		/**
		 * Gets the value of the dob property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getDob() {
			return dob;
		}

		/**
		 * Sets the value of the dob property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setDob(String value) {
			this.dob = value;
		}

		/**
		 * Gets the value of the planSelected property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getPlanSelected() {
			return planSelected;
		}

		/**
		 * Sets the value of the planSelected property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setPlanSelected(String value) {
			this.planSelected = value;
		}

		@Override
		public String toString() {
			return "CitigenData [firstName=" + firstName + ", lastName=" + lastName + ", gender=" + gender
					+ ", caseNum=" + caseNum + ", ssn=" + ssn + ", dob=" + dob + ", planSelected=" + planSelected + "]";
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within
	 * this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="snap-plan-data">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="family-income" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="is-employed" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="ccap-plan-data">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="kids-count" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="kids-age" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="parents-employed" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="family-income" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="medicaid-plan-data">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="employment-income" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="properties-cost" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="other-income" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "snapPlanData", "ccapPlanData", "medicaidPlanData" })
	public static class PlanDetails {

		@XmlElement(name = "snap-plan-data", required = true)
		protected EligibilityDetermination.PlanDetails.SnapPlanData snapPlanData;
		@XmlElement(name = "ccap-plan-data", required = true)
		protected EligibilityDetermination.PlanDetails.CcapPlanData ccapPlanData;
		@XmlElement(name = "medicaid-plan-data", required = true)
		protected EligibilityDetermination.PlanDetails.MedicaidPlanData medicaidPlanData;

		/**
		 * Gets the value of the snapPlanData property.
		 * 
		 * @return possible object is
		 *         {@link EligibilityDetermination.PlanDetails.SnapPlanData }
		 * 
		 */
		public EligibilityDetermination.PlanDetails.SnapPlanData getSnapPlanData() {
			return snapPlanData;
		}

		/**
		 * Sets the value of the snapPlanData property.
		 * 
		 * @param value allowed object is
		 *              {@link EligibilityDetermination.PlanDetails.SnapPlanData }
		 * 
		 */
		public void setSnapPlanData(EligibilityDetermination.PlanDetails.SnapPlanData value) {
			this.snapPlanData = value;
		}

		/**
		 * Gets the value of the ccapPlanData property.
		 * 
		 * @return possible object is
		 *         {@link EligibilityDetermination.PlanDetails.CcapPlanData }
		 * 
		 */
		public EligibilityDetermination.PlanDetails.CcapPlanData getCcapPlanData() {
			return ccapPlanData;
		}

		/**
		 * Sets the value of the ccapPlanData property.
		 * 
		 * @param value allowed object is
		 *              {@link EligibilityDetermination.PlanDetails.CcapPlanData }
		 * 
		 */
		public void setCcapPlanData(EligibilityDetermination.PlanDetails.CcapPlanData value) {
			this.ccapPlanData = value;
		}

		/**
		 * Gets the value of the medicaidPlanData property.
		 * 
		 * @return possible object is
		 *         {@link EligibilityDetermination.PlanDetails.MedicaidPlanData }
		 * 
		 */
		public EligibilityDetermination.PlanDetails.MedicaidPlanData getMedicaidPlanData() {
			return medicaidPlanData;
		}

		/**
		 * Sets the value of the medicaidPlanData property.
		 * 
		 * @param value allowed object is
		 *              {@link EligibilityDetermination.PlanDetails.MedicaidPlanData }
		 * 
		 */
		public void setMedicaidPlanData(EligibilityDetermination.PlanDetails.MedicaidPlanData value) {
			this.medicaidPlanData = value;
		}

		@Override
		public String toString() {
			return "PlanDetails [snapPlanData=" + snapPlanData + ", ccapPlanData=" + ccapPlanData
					+ ", medicaidPlanData=" + medicaidPlanData + "]";
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content contained within
		 * this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="kids-count" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="kids-age" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="parents-employed" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="family-income" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "kidsCount", "kidsAge", "parentsEmployed", "familyIncome" ,"planInfo"})
		public static class CcapPlanData implements IEDRules {

			@XmlElement(name = "kids-count", required = true)
			protected String kidsCount;
			@XmlElement(name = "kids-age", required = true)
			protected String kidsAge;
			@XmlElement(name = "parents-employed", required = true)
			protected String parentsEmployed;
			@XmlElement(name = "family-income", required = true)
			protected String familyIncome;
			@XmlElement(name = "plan-info",required = false)
			private PlanInfo planInfo;

			public PlanInfo getPlanInfo() {
				return planInfo;
			}

			public void setPlanInfo(PlanInfo planInfo) {
				this.planInfo = planInfo;
			}

			/**
			 * Gets the value of the kidsCount property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getKidsCount() {
				return kidsCount;
			}

			/**
			 * Sets the value of the kidsCount property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setKidsCount(String value) {
				this.kidsCount = value;
			}

			/**
			 * Gets the value of the kidsAge property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getKidsAge() {
				return kidsAge;
			}

			/**
			 * Sets the value of the kidsAge property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setKidsAge(String value) {
				this.kidsAge = value;
			}

			/**
			 * Gets the value of the parentsEmployed property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getParentsEmployed() {
				return parentsEmployed;
			}

			/**
			 * Sets the value of the parentsEmployed property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setParentsEmployed(String value) {
				this.parentsEmployed = value;
			}

			/**
			 * Gets the value of the familyIncome property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getFamilyIncome() {
				return familyIncome;
			}

			/**
			 * Sets the value of the familyIncome property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setFamilyIncome(String value) {
				this.familyIncome = value;
			}

			@Override
			public String toString() {
				return "CcapPlanData [kidsCount=" + kidsCount + ", kidsAge=" + kidsAge + ", parentsEmployed="
						+ parentsEmployed + ", familyIncome=" + familyIncome + "]";
			}

		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content contained within
		 * this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="employment-income" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="properties-cost" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="other-income" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "employmentIncome", "propertiesCost", "otherIncome","planInfo"})
		public static class MedicaidPlanData implements IEDRules {

			@XmlElement(name = "employment-income", required = true)
			protected String employmentIncome;
			@XmlElement(name = "properties-cost", required = true)
			protected String propertiesCost;
			@XmlElement(name = "other-income", required = true)
			protected String otherIncome;
			@XmlElement(name = "plan-info",required = false)
			private PlanInfo planInfo;

			public PlanInfo getPlanInfo() {
				return planInfo;
			}

			public void setPlanInfo(PlanInfo planInfo) {
				this.planInfo = planInfo;
			}

			/**
			 * Gets the value of the employmentIncome property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getEmploymentIncome() {
				return employmentIncome;
			}

			/**
			 * Sets the value of the employmentIncome property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setEmploymentIncome(String value) {
				this.employmentIncome = value;
			}

			/**
			 * Gets the value of the propertiesCost property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getPropertiesCost() {
				return propertiesCost;
			}

			/**
			 * Sets the value of the propertiesCost property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setPropertiesCost(String value) {
				this.propertiesCost = value;
			}

			/**
			 * Gets the value of the otherIncome property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getOtherIncome() {
				return otherIncome;
			}

			/**
			 * Sets the value of the otherIncome property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setOtherIncome(String value) {
				this.otherIncome = value;
			}

			@Override
			public String toString() {
				return "MedicaidPlanData [employmentIncome=" + employmentIncome + ", propertiesCost=" + propertiesCost
						+ ", otherIncome=" + otherIncome + "]";
			}

		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content contained within
		 * this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="family-income" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="is-employed" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "familyIncome", "isEmployed" ,"planInfo"})
		public static class SnapPlanData implements IEDRules {

			@XmlElement(name = "family-income", required = true)
			protected String familyIncome;
			@XmlElement(name = "is-employed", required = true)
			protected String isEmployed;
			@XmlElement(name = "plan-info",required = false)
			private PlanInfo planInfo;

			public PlanInfo getPlanInfo() {
				return planInfo;
			}

			public void setPlanInfo(PlanInfo planInfo) {
				this.planInfo = planInfo;
			}

			/**
			 * Gets the value of the familyIncome property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getFamilyIncome() {
				return familyIncome;
			}

			/**
			 * Sets the value of the familyIncome property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setFamilyIncome(String value) {
				this.familyIncome = value;
			}

			/**
			 * Gets the value of the isEmployed property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getIsEmployed() {
				return isEmployed;
			}

			/**
			 * Sets the value of the isEmployed property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setIsEmployed(String value) {
				this.isEmployed = value;
			}

			@Override
			public String toString() {
				return "SnapPlanData [familyIncome=" + familyIncome + ", isEmployed=" + isEmployed + "]";
			}

//			@Override
//			public PlanInfo executeRules(EligibilityDetermination eligibilityDetermination) {
//				KieServices ks = KieServices.Factory.get();
//				KieRepository kr = ks.getRepository();
//				KieFileSystem kfs = ks.newKieFileSystem();
//
//				kfs.write(ResourceFactory.newClassPathResource("rules/SnapRules.drl", this.getClass()));
//
//				KieBuilder kb = ks.newKieBuilder(kfs);
//
//				kb.buildAll(); // kieModule is automatically deployed to KieRepository if successfully built.
//				if (kb.getResults().hasMessages(Message.Level.ERROR)) {
//					throw new RuntimeException("Build Errors:\n" + kb.getResults().toString());
//				}
//
//				KieContainer kContainer = ks.newKieContainer(kr.getDefaultReleaseId());
//
//				KieSession kSession = kContainer.newKieSession();
//
//				SnapPlanData snapPlanData = eligibilityDetermination.getPlanDetails().getSnapPlanData();
//				
//				System.out.println("Inserting "+snapPlanData);
//				kSession.insert(snapPlanData);
//
//				System.out.println("Fire All Rules...");
//				kSession.fireAllRules();
//				kSession.dispose();
//				PlanInfo planInfo=snapPlanData.getPlanInfo();
//				System.out.println("PLANInfo : "+planInfo);
//				return planInfo;
//			}
		}

	}

	@Override
	public String toString() {
		return "EligibilityDetermination [citigenData=" + citigenData + ", planDetails=" + planDetails + "]";
	}

}
