//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.11 at 01:17:41 PM IST 
//

package com.ssa.ed.output;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="plan-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="plan-status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="case-num" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="plan-approved">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="plan-start-date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="plan-end-date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="benefit-amt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="plan-denied">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="denial-reason" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "planName", "planStatus", "caseNum", "planApproved", "planDenied" })
@XmlRootElement(name = "plan-info")
public class PlanInfo {

	@XmlElement(name = "plan-name", required = true)
	protected String planName;
	@XmlElement(name = "plan-status", required = true)
	protected String planStatus;
	@XmlElement(name = "case-num", required = true)
	protected String caseNum;
	@XmlElement(name = "plan-approved", required = true)
	protected PlanInfo.PlanApproved planApproved;
	@XmlElement(name = "plan-denied", required = true)
	protected PlanInfo.PlanDenied planDenied;

	/**
	 * Gets the value of the planName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPlanName() {
		return planName;
	}

	/**
	 * Sets the value of the planName property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setPlanName(String value) {
		this.planName = value;
	}

	/**
	 * Gets the value of the planStatus property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPlanStatus() {
		return planStatus;
	}

	@Override
	public String toString() {
		return "PlanInfo [planName=" + planName + ", planStatus=" + planStatus + ", caseNum=" + caseNum
				+ ", planApproved=" + planApproved + ", planDenied=" + planDenied + "]";
	}

	/**
	 * Sets the value of the planStatus property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setPlanStatus(String value) {
		this.planStatus = value;
	}

	/**
	 * Gets the value of the caseNum property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCaseNum() {
		return caseNum;
	}

	/**
	 * Sets the value of the caseNum property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setCaseNum(String value) {
		this.caseNum = value;
	}

	/**
	 * Gets the value of the planApproved property.
	 * 
	 * @return possible object is {@link PlanInfo.PlanApproved }
	 * 
	 */
	public PlanInfo.PlanApproved getPlanApproved() {
		return planApproved;
	}

	/**
	 * Sets the value of the planApproved property.
	 * 
	 * @param value allowed object is {@link PlanInfo.PlanApproved }
	 * 
	 */
	public void setPlanApproved(PlanInfo.PlanApproved value) {
		this.planApproved = value;
	}

	/**
	 * Gets the value of the planDenied property.
	 * 
	 * @return possible object is {@link PlanInfo.PlanDenied }
	 * 
	 */
	public PlanInfo.PlanDenied getPlanDenied() {
		return planDenied;
	}

	/**
	 * Sets the value of the planDenied property.
	 * 
	 * @param value allowed object is {@link PlanInfo.PlanDenied }
	 * 
	 */
	public void setPlanDenied(PlanInfo.PlanDenied value) {
		this.planDenied = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within
	 * this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="plan-start-date" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="plan-end-date" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="benefit-amt" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "planStartDate", "planEndDate", "benefitAmt" })
	public static class PlanApproved {

		@Override
		public String toString() {
			return "PlanApproved [planStartDate=" + planStartDate + ", planEndDate=" + planEndDate + ", benefitAmt="
					+ benefitAmt + "]";
		}

		@XmlElement(name = "plan-start-date", required = true)
		protected String planStartDate;
		@XmlElement(name = "plan-end-date", required = true)
		protected String planEndDate;
		@XmlElement(name = "benefit-amt", required = true)
		protected String benefitAmt;

		/**
		 * Gets the value of the planStartDate property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getPlanStartDate() {
			return planStartDate;
		}

		/**
		 * Sets the value of the planStartDate property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setPlanStartDate(String value) {
			this.planStartDate = value;
		}

		/**
		 * Gets the value of the planEndDate property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getPlanEndDate() {
			return planEndDate;
		}

		/**
		 * Sets the value of the planEndDate property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setPlanEndDate(String value) {
			this.planEndDate = value;
		}

		/**
		 * Gets the value of the benefitAmt property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getBenefitAmt() {
			return benefitAmt;
		}

		/**
		 * Sets the value of the benefitAmt property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setBenefitAmt(String value) {
			this.benefitAmt = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within
	 * this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="denial-reason" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "denialReason" })
	public static class PlanDenied {

		@XmlElement(name = "denial-reason", required = true)
		protected String denialReason;

		/**
		 * Gets the value of the denialReason property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getDenialReason() {
			return denialReason;
		}

		/**
		 * Sets the value of the denialReason property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setDenialReason(String value) {
			this.denialReason = value;
		}

		@Override
		public String toString() {
			return "PlanDenied [denialReason=" + denialReason + "]";
		}

	}

}
