#server port
server:
  port: 8082
  servlet:
    context-path: /SSAStateApp
  
#Profile (command line arg i.e --env=dev or -Denv=dev),View Resolver,Datasource, JPA 

spring:
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: sys
  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update
#send email
  mail:
    host: smtp.gmail.com
    port: 587
    username: vishalspring2019@gmail.com
    password: lasavi2019
    
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls: 
            enable: true
#Spring Security
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      
# logging configuration    
logging:
  level:
    org.springframework: ERROR
    com.ssa: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log

#Application config data

myapp:
  properties:
    mailFilePath: docs/ACC_CREATION_EMAIL_BODY_TEMPLATE.txt
    phoneno: 9812345678
    baseUrl: http://localhost:8082/SSAStateApp/login
    
    

